### ISSUE TITLE
Installing from scratch.

### ISSUE THREAD

**Issue by sarg** [chameco/tonic#1]
Hi there! I've decided to give your config a try, but stumbled upon issues installing it.
If I just clone the repo to `~/.emacs.d` - it won't work, because you rely on `use-package` but it's not bootstrapped. Also some modules should be checked out to `~/src/`, which I also don't have. And `~/etc/tonic/bookmarks.el`. In the end I've managed to run your config and quite liked it. Do you have a video demonstration of your daily work?

**Comment by chameco** [comment]
Hi, thanks for the feedback! As you've noticed, a bunch of stuff here currently depends on external tools/configuration or specifics of my own setup. Long-term, I'd like to make all of that easily configurable, but for now I don't quite have the time.

As far as boostrapping `use-package` goes, I manage all of my dependencies with Nix (see the `default.nix` file at the repository root), so I don't actually use `use-package` to fetch packages. It's pretty much just `require` with a nicer UI here.

I'd like to add a video or animated GIF to the `README.org` soon, since I think this configuration ends up looking pretty different from many Emacs setups. Stay tuned for that!
